spring.application.name=EccomPayment

spring.datasource.url=jdbc:mysql://localhost:3306/EcommerceDb
spring.datasource.username=root
spring.datasource.password=Nikku@456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8081

razorpay.keyId=rzp_test_Rj5QVbRN1FVkME
razorpay.keySecret=ubdQD16wTn3hOw0xCizio7Op

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prakharietdavv@gmail.com
spring.mail.password=gkmecklezdnbgtxr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

